// app/layout.js

import Providers from './providers';
import Navigation from './components/navigation_component';

// Seus fonts e metadata
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Providers>
          {/* Adicione o Navigation aqui, antes do children */}
          <Navigation /> 
          {children}
        </Providers>
      </body>
    </html>
  );
}